---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: voting-demo
spec:  
  replicas: 2
  template:
    metadata:
      labels:
        app: voting
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: result
        image: aloncodefresh/result:master
        ports:
        - containerPort: 80
        imagePullPolicy: Always
      - name: vote
        image: aloncodefresh/vote:master
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
      - name: worker
        image: aloncodefresh/worker:master
        imagePullPolicy: Always
