version: '2'
services:
  result:
    image: 'advance512/result:update-build'
    #build: ./result
    #command: node  server.js
    ports:
      - "1111:80"
    links:
      - "db:db"
    environment:
      - OPTION_A=$VOTING_OPTION_A
      - OPTION_B=$VOTING_OPTION_B
  worker:
    #build: ./worker
    image: 'advance512/worker:update-build'
    links:
      - "db:db"
      - "redis:redis"
  redis:
    image: 'redis:alpine'
    ports:
      - "6379"
  vote:
    #build: ./vote
    image: 'advance512/vote:update-build'
    command: python app.py
    ports:
      - "80"
    links:
      - "redis:redis"
    environment:
      - OPTION_A=$VOTING_OPTION_A
      - OPTION_B=$VOTING_OPTION_B
  db:
    image: 'postgres:9.4'
